### PR TITLE
fix: update docker image ref and remove loglevel

### PR DESCRIPTION
**Pull request by rhilgenbergbastos-ch**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by gjackson-ch — APPROVED** [review]

**Pull request merged**
